name: Python CI/CD Multi-OS

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ] 

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python ${{ matrix.python-version }} no ${{ matrix.os }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Instalar dependências
      shell: bash 
      run: |
        python -m pip install --upgrade pip
        # Esta sintaxe 'if' funcionará agora em todos os SOs
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    - name: Rodar Testes de Unidade
      run: |
        python -m unittest discover -s . -p 'test_*.py'