name: Python CI/CD Multi-OS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    # Define a matriz de sistemas operacionais e versões do Python
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    # O job será executado em cada combinação da matriz
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python ${{ matrix.python-version }} no ${{ matrix.os }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # Opcional: Cachear dependências do pip para builds mais rápidos

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        # Instala dependências se o arquivo requirements.txt existir
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    - name: Rodar Testes de Unidade
      run: |
        # Executa os testes de unidade usando unittest discover
        python -m unittest discover -s . -p 'test_*.py'